### ISSUE TITLE
? - Ободный мир

### ISSUE THREAD

**Issue by peachboy0** [romanin-rf/BiotechRussianTranslate#1]
- Что за `ободный мир`??

![Inkedunknown](https://user-images.githubusercontent.com/60302782/198737608-18095555-6ea3-4279-9e30-ed93e9b5d210.jpg)

**Comment by MarisKori** [comment]
<html>
<body>


Оригинал | Перевод
-- | --
deadworld | мёртвый мир
animal world | животный мир
medieval world | средневековый мир
steamworld | индустриальный мир
midworld | средний мир
urbworld | городской мир
glitterworld | утопический мир
rimworld | окраинный мир
toxic world | токсичный мир
glassworld, marble | «стеклянный шарик» или остеклевший мир
transcendent world | трансцендентный мир


</body>
</html>
