### ISSUE TITLE
Обучение - Tile inspector

### ISSUE THREAD

**Issue by peachboy0** [romanin-rf/BiotechRussianTranslate#10]
- **Обучение**
   - `Tile inspector`

![image](https://user-images.githubusercontent.com/60302782/198876772-08c819d1-fc2b-46ec-9572-84ad8950dea8.png)

**Comment by MarisKori** [comment]
Дословно - "досмотрщик тайла".
Нормально, думаю, - "Предпросмотр тайла".
"Вы можете изучить детали тайла, нажимая левый Alt. Это покажет..."
